export const GET_POSTS_REQUESTED = "GET_POSTS_REQUESTED";
export const GET_POST_BY_ID_REQUESTED = "GET_POST_BY_ID_REQUESTED";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POST_SUCCESS";
export const GET_POSTS_FAILED = "GET_POST_FAILED";
export const SEARCH_POSTS_REQUESTED = "SEARCH_POSTS_REQUESTED";
export const GET_SEARCH_POSTS_SUCCESS = "GET_SEARCH_POSTS_SUCCESS";
